// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ASetsgfB1G60UGsWI9tqzoqZoQtWmeo',
    appId: '1:483836574423:web:7e9ecf8afb4d4feb47ce92',
    messagingSenderId: '483836574423',
    projectId: 'it-polimi-dima',
    authDomain: 'it-polimi-dima.firebaseapp.com',
    storageBucket: 'it-polimi-dima.appspot.com',
    measurementId: 'G-W4JPM87564',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Vh4pb_s_Gw49XEgH-tvNOH239f1UTPQ',
    appId: '1:483836574423:android:023b7bdc8d17d0da47ce92',
    messagingSenderId: '483836574423',
    projectId: 'it-polimi-dima',
    storageBucket: 'it-polimi-dima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9iNVAhP2dXcnahNSRbPKncnbv4yC5Ve4',
    appId: '1:483836574423:ios:e71e0ba8d742fdbc47ce92',
    messagingSenderId: '483836574423',
    projectId: 'it-polimi-dima',
    storageBucket: 'it-polimi-dima.appspot.com',
    iosClientId: '483836574423-aub3fl78l1outknrm1fg4qjpj2f9fbfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9iNVAhP2dXcnahNSRbPKncnbv4yC5Ve4',
    appId: '1:483836574423:ios:e71e0ba8d742fdbc47ce92',
    messagingSenderId: '483836574423',
    projectId: 'it-polimi-dima',
    storageBucket: 'it-polimi-dima.appspot.com',
    iosClientId: '483836574423-aub3fl78l1outknrm1fg4qjpj2f9fbfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
